// Generated by PeachPy 0.2.0 from aez_amd64.py


// func xorBytes16AMD64SSE2(a *uint8, b *uint8, dst *uint8)
TEXT ·xorBytes16AMD64SSE2(SB),4,$0-24
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), BX
	MOVQ dst+16(FP), CX
	MOVOU 0(AX), X0
	MOVOU 0(BX), X1
	PXOR X1, X0
	MOVOU X0, 0(CX)
	RET
